# numpy.array基础

In [1]:
import numpy

In [3]:
numpy.__version__

'1.18.5'

In [4]:
import numpy as np

In [5]:
np.__version__

'1.18.5'

# PythonLIst的特点

In [6]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
L[5]

5

In [8]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [9]:
L[5] = "Machine learning"
L

[0, 1, 2, 3, 4, 'Machine learning', 6, 7, 8, 9]

In [10]:
# 效率低

In [11]:
import array
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [13]:
arr[5] = "machine learing"

TypeError: an integer is required (got type str)

## numpy.array

In [14]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
nparr[5] = "machine learning"

ValueError: invalid literal for int() with base 10: 'machine learning'

In [16]:
nparr.dtype

dtype('int64')

In [17]:
nparr[5] = 0.25

In [18]:
nparr.dtype

dtype('int64')

In [20]:
nparr
# 类型转换

array([0, 1, 2, 3, 4, 0, 6, 7, 8, 9])

In [21]:
nparr2 = np.array([1, 2, 3.1])

In [24]:
nparr2.dtype

dtype('float64')

## 其他创建 numpy.array的方法

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.zeros(shape=(1, 4), dtype=int)

array([[0, 0, 0, 0]])

In [33]:
np.full((3, 5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

## arange

In [34]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [36]:
np.arange(0, 20, 0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8,  2.1,  2.4,  2.7,  3. ,
        3.3,  3.6,  3.9,  4.2,  4.5,  4.8,  5.1,  5.4,  5.7,  6. ,  6.3,
        6.6,  6.9,  7.2,  7.5,  7.8,  8.1,  8.4,  8.7,  9. ,  9.3,  9.6,
        9.9, 10.2, 10.5, 10.8, 11.1, 11.4, 11.7, 12. , 12.3, 12.6, 12.9,
       13.2, 13.5, 13.8, 14.1, 14.4, 14.7, 15. , 15.3, 15.6, 15.9, 16.2,
       16.5, 16.8, 17.1, 17.4, 17.7, 18. , 18.3, 18.6, 18.9, 19.2, 19.5,
       19.8])

### linspace(等长的截出几个点)

In [37]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

### random 随机数

In [38]:
np.random.randint(0, 10)

5

In [39]:
np.random.randint(0, 10, 6)

array([7, 3, 7, 2, 3, 4])

In [41]:
np.random.randint(4, 80, size=(2, 6))

array([[37, 75, 31,  5, 67, 73],
       [23, 29, 61, 33,  5, 56]])

### 一样的随机种子 数

In [52]:
np.random.seed(666)

In [55]:
np.random.randint(1, 20, 5)
# np.random.randint(1, 20, 5)

array([ 5, 15,  2, 17, 15])

In [56]:
np.random.seed(666)
np.random.randint(1, 20, 5)

array([13,  3, 14,  7, 10])

In [57]:
np.random.random(5)

array([0.75033054, 0.33596835, 0.24434285, 0.25987554, 0.28116849])

In [59]:
np.random.normal(10, 100)

-11.725990311138087

In [60]:
np.random.normal(10, 100, size=(2, 5))

array([[  75.51732983,   64.68659307, -152.52001749,  -80.77283341,
          58.03148742],
       [ -60.52673385,   77.06843845,   53.40469389,   88.33709216,
         -37.08266661]])

In [61]:
np.random.normal?

In [62]:
np.random?

In [63]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : fl