# Numpy.array的基本操作

In [2]:
import numpy as np

In [3]:
x = np.arange(15).reshape(3, 5)

In [4]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
x.ndim

2

In [6]:
x.ndim

2

In [7]:
x.shape

(3, 5)

In [8]:
x.size

15

## numpy.array的数据访问

In [9]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
x[5]

IndexError: index 5 is out of bounds for axis 0 with size 3

In [11]:
x[2[3]]

<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
<ipython-input-11-06c12255d62c>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  x[2[3]]


TypeError: 'int' object is not subscriptable

In [12]:
x[2][3]

13

In [13]:
x[(2, 3)]

13

In [14]:
x[2, 3]

13

In [15]:
x[2, :3]

array([10, 11, 12])

In [17]:
x[:, :2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

## 合并操作

In [3]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [19]:
x

array([1, 2, 3])

In [20]:
y

array([3, 2, 1])

In [1]:
import numpy

In [2]:
import numpy as np

In [4]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [6]:
z = np.array([666, 66, 666])

In [8]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666,  66, 666])

In [9]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])

In [10]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [11]:
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [12]:
A.shape

(2, 3)

In [13]:
np.concatenate([A, z])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [14]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666,  66, 666]])

In [15]:
A2 = np.concatenate([A, z.reshape(1, -1)])

In [16]:
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666,  66, 666]])

In [17]:
# 垂直方向的叠加
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666,  66, 666]])

In [18]:
z = np.array([666, 666, 666, 666])

In [19]:
np.vstack([A, z])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [20]:
z = np.array([666, 66, 666])

In [23]:
# 说水平方向的叠加
B = np.full((2, 2), 100)
B

array([[100, 100],
       [100, 100]])

In [24]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [25]:
np.hstack([A, z])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

## 分割操作

In [26]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.split(x, [3, 7])

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]