# numpy.array 中的运算

In [1]:
n = 10
L = [i for i in range(n)]

In [2]:
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
A = []
for a in L:
    A.append(2*a)

In [4]:
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [5]:
n = 1000000
L = [i for i in range(n)]

In [6]:
%%time
A = []
for a in L:
    A.append(2*a)

CPU times: user 118 ms, sys: 19.3 ms, total: 138 ms
Wall time: 137 ms


In [7]:
%%time
A = [2*e for e in L]

CPU times: user 59.9 ms, sys: 27.7 ms, total: 87.5 ms
Wall time: 86.6 ms


In [8]:
import numpy as np
L = np.arange(n)

In [9]:
%%time
A = np.array(2*e for e in L)

CPU times: user 11.2 ms, sys: 5.17 ms, total: 16.4 ms
Wall time: 16 ms


In [10]:
%%time
A = 2*L
A

CPU times: user 2.46 ms, sys: 5.13 ms, total: 7.59 ms
Wall time: 6.63 ms


array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [12]:
%%time
n = 10
L = np.arange(n)
2 * L

CPU times: user 88 µs, sys: 12 µs, total: 100 µs
Wall time: 86.1 µs


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Universal Functions

In [14]:
X = np.arange(1, 16).reshape((3, 5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [15]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [16]:
X - 1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [18]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [19]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [20]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [21]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [22]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [23]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [24]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [25]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [26]:
np.tanh(X)

array([[0.76159416, 0.96402758, 0.99505475, 0.9993293 , 0.9999092 ],
       [0.99998771, 0.99999834, 0.99999977, 0.99999997, 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ]])

In [27]:
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [28]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [30]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

## 矩阵之间的运算

In [31]:
A = np.arange(4).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [32]:
B = np.full((2, 2), 10)
B

array([[10, 10],
       [10, 10]])

In [33]:
A + B

array([[10, 11],
       [12, 13]])

In [34]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [35]:
A * B

array([[ 0, 10],
       [20, 30]])

In [36]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [37]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [38]:
A

array([[0, 1],
       [2, 3]])

In [39]:
A.T

array([[0, 2],
       [1, 3]])

## 向量和矩阵的运算

In [40]:
v = np.array([1, 2])
A

array([[0, 1],
       [2, 3]])

In [41]:
v + A

array([[1, 3],
       [3, 5]])

In [42]:
v

array([1, 2])

In [43]:
np.vstack([v]*A.shape[0])

array([[1, 2],
       [1, 2]])

In [44]:
np.vstack([v]*A.shap[0]) + A

AttributeError: 'numpy.ndarray' object has no attribute 'shap'

In [45]:
np.tile(v, (2, 1))

array([[1, 2],
       [1, 2]])

In [46]:
v + A

array([[1, 3],
       [3, 5]])