# 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iria = datasets.load_iris()

In [3]:
X = iria.data
y = iria.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

## 1.train_text_split

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

X

In [8]:
shuffle_indexes = np.random.permutation(len(X))

In [9]:
shuffle_indexes

array([ 95,  51,   7,   9,  84, 149,   2,  37, 146,  56, 133,  46, 148,
       139,  21,  68, 110,  99,  69,  13, 135, 117,  35, 129,  36, 112,
        66,  93,  43,  22, 118,  81, 144, 122,  45,   4,  61, 107,  94,
        65,   1, 103,   0,  55,  96, 113,  41,  90,  44,  19,  72, 120,
        92,  23,  17,  89,  14, 127,  38,  28,  83, 132, 145,  67, 128,
        42,  27, 131,   3, 138,  91, 136,  24,   5, 102, 121, 147, 134,
       114,  70,  79,  40, 123,  63,  87, 142,  26,  33,  32,   6,  58,
        80,  52,  16, 125,  53, 109,  73, 100, 111,  82,  97,  76,  60,
        71,  49, 137,   8,  29,  98, 105, 126,  48, 101,  34,  15,  10,
        30,  11,  77,  74, 143,  31,  59, 140, 124,  86,  47, 115, 130,
        54, 108,  25,  78,  85, 106,  62,  39,  50, 119,  12,  64,  88,
       104,  20,  75,  57, 141,  18, 116])

In [10]:
text_ratio = 0.2
text_size = int(len(X)*text_ratio)

In [11]:
text_size

30

In [12]:
text_indexes = shuffle_indexes[:text_size]
train_indexes = shuffle_indexes[text_size:]

In [13]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_text = X[text_indexes]
y_text = y[text_indexes]

In [14]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [1]:
 %run KNN.py

In [16]:
my_knn_clf = KNNClassifier(k = 3)

In [17]:
my_knn_clf.fit(X_train = X_train, y_train = y_train)

KNN(k=3)

In [18]:
y_predict = my_knn_clf.predict(X_text)

In [19]:
y_predict

array([1, 2, 0, 0, 1, 2, 0, 0, 2, 1, 2, 0, 2, 2, 0, 1, 2, 1, 1, 0, 2, 2,
       0, 2, 0, 2, 1, 1, 0, 0])

In [20]:
y_text

array([1, 1, 0, 0, 1, 2, 0, 0, 2, 1, 2, 0, 2, 2, 0, 1, 2, 1, 1, 0, 2, 2,
       0, 2, 0, 2, 1, 1, 0, 0])

In [21]:
sum(y_predict == y_text)

29

## 2.预测准确率

In [22]:
sum(y_predict == y_text) / len(y_text)

0.9666666666666667

## 3.sklearn 的 train_text_split

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_text, y_train, y_text = train_test_split(X, y)

In [25]:
print(X_train.shape)
print(y_train.shape)

(112, 4)
(112,)


In [31]:
my_knn_clf = KNNClassifier(k = 3)
my_knn_clf.fit(X_train = X_train, y_train = y_train)
y_predict = my_knn_clf.predict(X_text)
y_predict.shape

(38,)

In [27]:
y_predict

array([2, 2, 1, 0, 1, 0, 2, 1, 2, 0, 0, 1, 0, 1, 0, 1, 2, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 2])

In [28]:
y_text

array([2, 2, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 2, 2, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 2, 2, 1, 0, 2])

In [29]:
sum(y_predict == y_text)

34

In [30]:
sum(y_predict == y_text) / len(y_text)

0.8947368421052632